backend:
  name: git-gateway
  # repo: buzzlightyear182/blackdog-website # Path to your Github repository
  branch: master # Branch to update (master by default)
  
media_folder: "source/blog/images" # Folder where user uploaded files should go
public_folder: "/blog/images" # CMS now knows 'source' is the public folder and will strip this from the path

publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "news" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Create News Article" # Used in the UI, ie.: "New Post"
    folder: "source/blog/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Category", name: "category", widget: "hidden", default: "news"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Featured Image", name: "cover_image", widget: "image"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Summary", name: "metadescription", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "learning-zone" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Create Learning Zone Article" # Used in the UI, ie.: "New Post"
    folder: "source/blog/learning-zone" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Category", name: "category", widget: "hidden", default: "learning-zone"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Featured Image", name: "cover_image", widget: "image"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}